# Service description for Anker Solix custom integration

get_solarbank_schedule:
  fields:
    entity_id:
      example: "sensor.solarbank_e1600_home_preset"
      required: true
      selector:
        entity:
          filter:
            integration: anker_solix
            domain: sensor
            supported_features:
              - 1
set_solarbank_schedule:
  fields:
    entity_id:
      example: "sensor.solarbank_e1600_home_preset"
      required: true
      selector:
        entity:
          filter:
            integration: anker_solix
            domain: sensor
            supported_features:
              - 1
    start_time:
      required: true
      example: "00:00:00"
      default: "00:00:00"
      selector:
        time:
    end_time:
      required: true
      example: "23:59:00"
      default: "23:59:00"
      selector:
        time:
    appliance_load:
      required: false
      example: 100
      default: 100
      selector:
        number:
          min: 0
          max: 800
          step: 10
          unit_of_measurement: "W"
    allow_export:
      required: false
      example: "True"
      selector:
        boolean:
    charge_priority_limit:
      required: false
      example: 80
      default: 80
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
update_solarbank_schedule:
  fields:
    entity_id:
      example: "sensor.solarbank_e1600_home_preset"
      required: true
      selector:
        entity:
          filter:
            integration: anker_solix
            domain: sensor
            supported_features:
              - 1
    start_time:
      required: true
      example: "00:00:00"
      default: "00:00:00"
      selector:
        time:
    end_time:
      required: true
      example: "23:59:00"
      default: "23:59:00"
      selector:
        time:
    appliance_load:
      required: false
      example: 0
      default: 100
      selector:
        number:
          min: 0
          max: 800
          step: 10
          unit_of_measurement: "W"
    allow_export:
      required: false
      example: "True"
      selector:
        boolean:
    charge_priority_limit:
      required: false
      example: 80
      default: 80
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
